[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/api/novo-lead"
  to = "/.netlify/functions/novo-lead"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[build.environment]
  NODE_VERSION = "18"