[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[[redirects]]
  from = "/api/novo-lead"
  to = "/.netlify/functions/novo-lead"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
