[build]
  functions = "functions"

[dev]
  targetPort = 0
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/api/novo-lead"
  to = "/.netlify/functions/novo-lead"
  status = 200
  force = true
